export const config = {
  name: 'My Fendisha 🍿',
  birthday: '18 August 2026',
  age: 21,
  passcode: '521152',
  passcodeClue: 'The day that changed what “us” meant. The broken glass reads it from the other side.',
  phone: '+251960306801',
  preview: new URLSearchParams(location.search).has('preview'),
};

export const media = {
  frfr: '/art/frfr-cafe-reimagined.svg',
  gate: '/art/aau-fifth-gate-reimagined.svg',
  kidane: '/art/kidane-mihret-line.svg',
  firstDate: '/media/photos/first-date.jpg',
  laugh: '/media/photos/fendisha-laugh.jpg',
  mad: '/media/photos/fendisha-mad.jpg',
  library: '/media/photos/library.jpg',
  basketball: '/media/photos/basketball.jpg',
  bowling: '/media/photos/bowling.jpg',
  cinema: '/media/photos/cinema.jpg',
  kukuye: '/media/photos/kukuye.jpg',
  ginfle: '/media/photos/ginfle.jpg',
  concert: '/media/photos/concert.jpg',
  airport: '/media/photos/airport.jpg',
  walking: '/media/photos/walking.jpg',
  kemis: '/media/photos/kemis-netela.jpg',
  gondar: '/media/photos/gondar.jpg',
  favorite: '/media/photos/favorite-her.jpg',
  heroCollage: '/media/photos/favorite-her.jpg',
  childhood: '/media/photos/childhood.jpg',
  handwritten: '/media/photos/handwritten-letter.jpg',
  voiceOpening: '/media/voice/01-opening.mp3',
  voiceCalls: '/media/voice/02-calls.mp3',
  voiceDistance: '/media/voice/03-distance.mp3',
  voiceFaith: '/media/voice/04-faith.mp3',
  voiceFuture: '/media/voice/05-future.mp3',
  voiceFinal: '/media/voice/06-final-birthday.mp3',
  laughAudio: '/media/voice/fendisha-laugh.mp3',
};
